services:
  organizationboard-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-user:/var/opt/mssql
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr"]
      interval: 10s
      retries: 1
      start_period: 60s
      timeout: 5s

  organizationboard:
    build:
      context: .
      dockerfile: OrganizationBoard/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8080:8080
    networks:
      - app-net
    depends_on:
      migration_service:
        condition: service_completed_successfully

  migration_service:
    build:
      context: .
      dockerfile: EFrameWork/Dockerfile
    depends_on:
      organizationboard-db:
        condition: service_healthy

  orgweb:
    build:
      context: ./orgweb
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  agent-python:
    build:
      context: .
      dockerfile: LLMExamAgents/Dockerfile
    ports:
      - "8008:8008"
    networks:
      - app-net

volumes:
  mssql-user:

networks:
  app-net:
    driver: bridge