// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace OrganizationBoard.Tests.ServiceTests.BlackBox_Specs
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UserLoginAndAccountCreationFeature : object, Xunit.IClassFixture<UserLoginAndAccountCreationFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en"), "ServiceTests/BlackBox.Specs", "User Login and Account Creation", "  As a user of the Organization Board application\r\n  I want to be able to log in " +
                "and create new accounts\r\n  So that I can access and manage my organization\'s boa" +
                "rds and tasks", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Login.feature"
#line hidden
        
        public UserLoginAndAccountCreationFeature(UserLoginAndAccountCreationFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successful User Login with Valid Credentials")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Successful User Login with Valid Credentials")]
        public async global::System.Threading.Tasks.Task SuccessfulUserLoginWithValidCredentials()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful User Login with Valid Credentials", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 12
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("a user with email \"test@example.com\" and password \"hashedPassword\" exists in the " +
                        "database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.AndAsync("the RSA service will decrypt \"encryptedPassword\" to \"decryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.AndAsync("the BCrypt service will verify \"decryptedPassword\" against \"hashedPassword\" as tr" +
                        "ue", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.WhenAsync("the user attempts to log in with email \"test@example.com\" and password \"encrypted" +
                        "Password\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.ThenAsync("the login should be successful and the user details are returned", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login Fails with Invalid Email")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Login Fails with Invalid Email")]
        public async global::System.Threading.Tasks.Task LoginFailsWithInvalidEmail()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login Fails with Invalid Email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("no user with email \"wrong@example.com\" exists in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("the user attempts to log in with email \"wrong@example.com\" and password \"anyPassw" +
                        "ord\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("an UnauthorizedAccessException should be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login Fails with Invalid Password")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Login Fails with Invalid Password")]
        public async global::System.Threading.Tasks.Task LoginFailsWithInvalidPassword()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login Fails with Invalid Password", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("a user with email \"test@example.com\" and password \"hashedPassword\" exists in the " +
                        "database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.AndAsync("the RSA service will decrypt \"wrongEncryptedPassword\" to \"decryptedWrongPassword\"" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("the BCrypt service will verify \"decryptedWrongPassword\" against \"hashedPassword\" " +
                        "as false", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.WhenAsync("the user attempts to log in with email \"test@example.com\" and password \"wrongEncr" +
                        "yptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("an UnauthorizedAccessException should be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login Fails due to RSA Decryption Error")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Login Fails due to RSA Decryption Error")]
        public async global::System.Threading.Tasks.Task LoginFailsDueToRSADecryptionError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login Fails due to RSA Decryption Error", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
    await testRunner.GivenAsync("a user with email \"test@example.com\" and password \"hashedPassword\" exists in the " +
                        "database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
    await testRunner.AndAsync("the RSA service throws an exception when decrypting \"encryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.WhenAsync("the user attempts to log in with email \"test@example.com\" and password \"encrypted" +
                        "Password\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
    await testRunner.ThenAsync("an ApplicationException with message \"Something went wrong while logging in.\" sho" +
                        "uld be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login Fails due to BCrypt Verification Error")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Login Fails due to BCrypt Verification Error")]
        public async global::System.Threading.Tasks.Task LoginFailsDueToBCryptVerificationError()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login Fails due to BCrypt Verification Error", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 38
    await testRunner.GivenAsync("a user with email \"test@example.com\" and password \"hashedPassword\" exists in the " +
                        "database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 39
    await testRunner.AndAsync("the RSA service will decrypt \"encryptedPassword\" to \"decryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("the BCrypt service throws an exception when verifying \"decryptedPassword\" against" +
                        " \"hashedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.WhenAsync("the user attempts to log in with email \"test@example.com\" and password \"encrypted" +
                        "Password\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
    await testRunner.ThenAsync("an ApplicationException with message \"Something went wrong while logging in.\" sho" +
                        "uld be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login Fails with Email at Minimum Invalid Length (BVT)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Login Fails with Email at Minimum Invalid Length (BVT)")]
        public async global::System.Threading.Tasks.Task LoginFailsWithEmailAtMinimumInvalidLengthBVT()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login Fails with Email at Minimum Invalid Length (BVT)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 46
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
    await testRunner.GivenAsync("a user with email \"valid@example.com\" and password \"hashedPassword\" exists in the" +
                        " database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
    await testRunner.AndAsync("the RSA service will decrypt \"encryptedPassword\" to \"decryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.WhenAsync("the user attempts to log in with email \"a@a.c\" and password \"encryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
    await testRunner.ThenAsync("an UnauthorizedAccessException with message \"Attempted to perform an unauthorized" +
                        " operation.\" should be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login Fails with Email Containing Invalid Format (ECT)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Login Fails with Email Containing Invalid Format (ECT)")]
        public async global::System.Threading.Tasks.Task LoginFailsWithEmailContainingInvalidFormatECT()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login Fails with Email Containing Invalid Format (ECT)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 53
    await testRunner.GivenAsync("a user with email \"test@example.com\" and password \"hashedPassword\" exists in the " +
                        "database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
    await testRunner.AndAsync("the RSA service will decrypt \"encryptedPassword\" to \"decryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
    await testRunner.WhenAsync("the user attempts to log in with email \"invalid-email\" and password \"encryptedPas" +
                        "sword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
    await testRunner.ThenAsync("a ValidationException with message \"Invalid email or password\" should be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login Fails with Missing Email (Required attribute)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Login Fails with Missing Email (Required attribute)")]
        public async global::System.Threading.Tasks.Task LoginFailsWithMissingEmailRequiredAttribute()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login Fails with Missing Email (Required attribute)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 59
    await testRunner.GivenAsync("a user with email \"test@example.com\" and password \"hashedPassword\" exists in the " +
                        "database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
    await testRunner.AndAsync("the RSA service will decrypt \"encryptedPassword\" to \"decryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.WhenAsync("the user attempts to log in with email \"\" and password \"encryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
    await testRunner.ThenAsync("a ValidationException with message \"The Email field is required.\" should be throw" +
                        "n", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Login Fails with Missing Password (Required attribute)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Login Fails with Missing Password (Required attribute)")]
        public async global::System.Threading.Tasks.Task LoginFailsWithMissingPasswordRequiredAttribute()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Login Fails with Missing Password (Required attribute)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
    await testRunner.GivenAsync("a user with email \"test@example.com\" and password \"hashedPassword\" exists in the " +
                        "database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 66
    await testRunner.AndAsync("the RSA service will decrypt \"encryptedPassword\" to \"decryptedPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
    await testRunner.WhenAsync("the user attempts to log in with email \"test@example.com\" and password \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
    await testRunner.ThenAsync("a ValidationException with message \"Invalid email or password\" should be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Successful Account and Organization Creation")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Successful Account and Organization Creation")]
        public async global::System.Threading.Tasks.Task SuccessfulAccountAndOrganizationCreation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Successful Account and Organization Creation", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 72
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 73
    await testRunner.GivenAsync("the \"Admin\" role exists in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 74
    await testRunner.AndAsync("the BCrypt service will hash \"newPassword123!\" to \"hashedNewPassword123!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.WhenAsync("a new account is created with email \"newuser@example.com\", password \"newPassword1" +
                        "23!\", and organization \"NewOrg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
    await testRunner.ThenAsync("a new organization \"NewOrg\" should be saved to the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 77
    await testRunner.AndAsync("a new user \"newuser@example.com\" with \"hashedNewPassword123!\" and \"Admin\" role fo" +
                        "r \"NewOrg\" should be saved to the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Account and Organization Creation Fails due to Database Error during User Save")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Account and Organization Creation Fails due to Database Error during User Save")]
        public async global::System.Threading.Tasks.Task AccountAndOrganizationCreationFailsDueToDatabaseErrorDuringUserSave()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Account and Organization Creation Fails due to Database Error during User Save", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 79
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 80
    await testRunner.GivenAsync("the \"Admin\" role exists in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 81
    await testRunner.AndAsync("the BCrypt service will hash \"P@ssw0rd1\" to \"hashedNewPassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.AndAsync("the organization \"NewOrg\" is successfully saved", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("a database error occurs when saving the user \"newuser@example.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 84
    await testRunner.WhenAsync("a new account is created with email \"newuser@example.com\", password \"P@ssw0rd1\", " +
                        "and organization \"NewOrg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
    await testRunner.ThenAsync("an ApplicationException with message \"Something went wrong while logging in.\" sho" +
                        "uld be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Account Creation Fails with Missing Email (Required attribute)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Account Creation Fails with Missing Email (Required attribute)")]
        public async global::System.Threading.Tasks.Task AccountCreationFailsWithMissingEmailRequiredAttribute()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Account Creation Fails with Missing Email (Required attribute)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 89
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 90
    await testRunner.GivenAsync("the \"Admin\" role exists in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
    await testRunner.AndAsync("the BCrypt service will hash \"password123!\" to \"hashedPassword123!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
    await testRunner.WhenAsync("a new account is created with email \"\", password \"password123!\", and organization" +
                        " \"ValidOrg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 93
    await testRunner.ThenAsync("a ValidationException with message \"The Email field is required.\" should be throw" +
                        "n", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Account Creation Fails with Email Containing Invalid Format (ECT)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Account Creation Fails with Email Containing Invalid Format (ECT)")]
        public async global::System.Threading.Tasks.Task AccountCreationFailsWithEmailContainingInvalidFormatECT()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Account Creation Fails with Email Containing Invalid Format (ECT)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 95
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 96
    await testRunner.GivenAsync("the \"Admin\" role exists in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
    await testRunner.AndAsync("the BCrypt service will hash \"password123!\" to \"hashedPassword123!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.WhenAsync("a new account is created with email \"invalid-email-format\", password \"password123" +
                        "!\", and organization \"ValidOrg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 99
    await testRunner.ThenAsync("a ValidationException with message \"Invalid email format.\" should be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Account Creation Fails with Password Lacking Required Complexity (ECT)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Account Creation Fails with Password Lacking Required Complexity (ECT)")]
        public async global::System.Threading.Tasks.Task AccountCreationFailsWithPasswordLackingRequiredComplexityECT()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Account Creation Fails with Password Lacking Required Complexity (ECT)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 101
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 102
    await testRunner.GivenAsync("the \"Admin\" role exists in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
    await testRunner.AndAsync("the BCrypt service will hash \"simplepassword123\" to \"hashedSimplePassword\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
    await testRunner.WhenAsync("a new account is created with email \"newuser@example.com\", password \"simplepasswo" +
                        "rd123\", and organization \"ValidOrg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
    await testRunner.ThenAsync("a ValidationException with message \"Password must be at least 8 characters long, " +
                        "contain at least one uppercase letter, one number, and one special character.\" s" +
                        "hould be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Account Creation Fails with Missing Password (Required attribute)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Account Creation Fails with Missing Password (Required attribute)")]
        public async global::System.Threading.Tasks.Task AccountCreationFailsWithMissingPasswordRequiredAttribute()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Account Creation Fails with Missing Password (Required attribute)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 107
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
    await testRunner.GivenAsync("the \"Admin\" role exists in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
    await testRunner.AndAsync("the BCrypt service will hash \"\" to \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
    await testRunner.WhenAsync("a new account is created with email \"newuser@example.com\", password \"\", and organ" +
                        "ization \"ValidOrg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
    await testRunner.ThenAsync("a ValidationException with message \"The Password field is required.\" should be th" +
                        "rown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Account Creation Fails with Missing Organization Name (Required attribute)")]
        [Xunit.TraitAttribute("FeatureTitle", "User Login and Account Creation")]
        [Xunit.TraitAttribute("Description", "Account Creation Fails with Missing Organization Name (Required attribute)")]
        public async global::System.Threading.Tasks.Task AccountCreationFailsWithMissingOrganizationNameRequiredAttribute()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Account Creation Fails with Missing Organization Name (Required attribute)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 113
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 114
    await testRunner.GivenAsync("the \"Admin\" role exists in the database", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
    await testRunner.AndAsync("the BCrypt service will hash \"password123!\" to \"hashedPassword123!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
    await testRunner.WhenAsync("a new account is created with email \"newuser@example.com\", password \"Password123!" +
                        "\", and organization \"\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
    await testRunner.ThenAsync("a ValidationException with message \"Organization name is required.\" should be thr" +
                        "own", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UserLoginAndAccountCreationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UserLoginAndAccountCreationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
