<<<<<<<< HEAD:EFrameWork/Migrations/20250515085538_ChangingModels.Designer.cs
﻿// <auto-generated />
using System;
using EFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFrameWork.Migrations
{
    [DbContext(typeof(OBDbContext))]
    [Migration("20250515085538_ChangingModels")]
    partial class ChangingModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFrameWork.Model.Board", b =>
                {
                    b.Property<int>("BoardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardID"));

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("BoardID");

                    b.HasIndex("TeamID");

                    b.ToTable("BoardTables");
                });

            modelBuilder.Entity("EFrameWork.Model.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationID"));

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationID");

                    b.ToTable("OrganizationTables");

                    b.HasData(
                        new
                        {
                            OrganizationID = 1,
                            OrganizationName = "Lars"
                        });
                });

            modelBuilder.Entity("EFrameWork.Model.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("BoardID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Estimation")
                        .HasColumnType("real");

                    b.Property<float?>("NumUser")
                        .HasColumnType("real");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("BoardID");

                    b.HasIndex("StatusID");

                    b.ToTable("TaskTables");
                });

            modelBuilder.Entity("EFrameWork.Model.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.ToTable("TeamTables");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            TeamName = "team 1"
                        },
                        new
                        {
                            TeamID = 2,
                            TeamName = "team 2"
                        });
                });

            modelBuilder.Entity("EFrameWork.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("RoleID");

                    b.HasIndex("TeamID");

                    b.ToTable("UserTables");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "Mail1",
                            OrganizationID = 1,
                            Password = "1234",
                            RoleID = 1,
                            TeamID = 1
                        },
                        new
                        {
                            UserID = 2,
                            Email = "Mail2",
                            OrganizationID = 1,
                            Password = "1234",
                            RoleID = 2,
                            TeamID = 2
                        },
                        new
                        {
                            UserID = 3,
                            Email = "Mail3",
                            OrganizationID = 1,
                            Password = "1234",
                            RoleID = 3,
                            TeamID = 1
                        });
                });

            modelBuilder.Entity("EFrameWork.Model.UserToTask", b =>
                {
                    b.Property<int>("UserToTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserToTaskID"));

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserToTaskID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("UserToTaskTables");
                });

            modelBuilder.Entity("Model.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role");

                    b.HasKey("RoleID");

                    b.ToTable("RoleTables");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Team Leader"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Team Member"
                        });
                });

            modelBuilder.Entity("Model.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Status");

                    b.HasKey("StatusID");

                    b.ToTable("StatusTables");

                    b.HasData(
                        new
                        {
                            StatusID = 1,
                            TaskStatus = "To Do"
                        },
                        new
                        {
                            StatusID = 2,
                            TaskStatus = "In Progress"
                        },
                        new
                        {
                            StatusID = 3,
                            TaskStatus = "Done"
                        },
                        new
                        {
                            StatusID = 4,
                            TaskStatus = "Confirmed"
                        });
                });

            modelBuilder.Entity("EFrameWork.Model.Board", b =>
                {
                    b.HasOne("EFrameWork.Model.Team", "Team")
                        .WithMany("Boards")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EFrameWork.Model.Task", b =>
                {
                    b.HasOne("EFrameWork.Model.Board", "Board")
                        .WithMany("Tasks")
                        .HasForeignKey("BoardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Status", "Status")
                        .WithMany("Tasks")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("EFrameWork.Model.User", b =>
                {
                    b.HasOne("EFrameWork.Model.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFrameWork.Model.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EFrameWork.Model.UserToTask", b =>
                {
                    b.HasOne("EFrameWork.Model.Task", "Task")
                        .WithMany("UserAssignments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFrameWork.Model.User", "User")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EFrameWork.Model.Board", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("EFrameWork.Model.Organization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EFrameWork.Model.Task", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("EFrameWork.Model.Team", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EFrameWork.Model.User", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Model.Status", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
========
﻿// <auto-generated />
using System;
using EFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFrameWork.Migrations
{
    [DbContext(typeof(OBDbContext))]
    [Migration("20250515092236_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFrameWork.Model.Board", b =>
                {
                    b.Property<int>("BoardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoardID"));

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("BoardID");

                    b.HasIndex("TeamID");

                    b.ToTable("BoardTables");
                });

            modelBuilder.Entity("EFrameWork.Model.Organization", b =>
                {
                    b.Property<int>("OrganizationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationID"));

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrganizationID");

                    b.ToTable("OrganizationTables");

                    b.HasData(
                        new
                        {
                            OrganizationID = 1,
                            OrganizationName = "Lars"
                        });
                });

            modelBuilder.Entity("EFrameWork.Model.Task", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskID"));

                    b.Property<int>("BoardID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("Estimation")
                        .HasColumnType("real");

                    b.Property<float?>("NumUser")
                        .HasColumnType("real");

                    b.Property<int>("StatusID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskID");

                    b.HasIndex("BoardID");

                    b.HasIndex("StatusID");

                    b.ToTable("TaskTables");
                });

            modelBuilder.Entity("EFrameWork.Model.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamID");

                    b.ToTable("TeamTables");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            TeamName = "team 1"
                        },
                        new
                        {
                            TeamID = 2,
                            TeamName = "team 2"
                        });
                });

            modelBuilder.Entity("EFrameWork.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("OrganizationID");

                    b.HasIndex("RoleID");

                    b.HasIndex("TeamID");

                    b.ToTable("UserTables");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "Mail1",
                            OrganizationID = 1,
                            Password = "1234",
                            RoleID = 1
                        },
                        new
                        {
                            UserID = 2,
                            Email = "Mail2",
                            OrganizationID = 1,
                            Password = "1234",
                            RoleID = 2,
                            TeamID = 2
                        },
                        new
                        {
                            UserID = 3,
                            Email = "Mail3",
                            OrganizationID = 1,
                            Password = "1234",
                            RoleID = 3,
                            TeamID = 1
                        });
                });

            modelBuilder.Entity("EFrameWork.Model.UserToTask", b =>
                {
                    b.Property<int>("UserToTaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserToTaskID"));

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserToTaskID");

                    b.HasIndex("TaskID");

                    b.HasIndex("UserID");

                    b.ToTable("UserToTaskTables");
                });

            modelBuilder.Entity("Model.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Role");

                    b.HasKey("RoleID");

                    b.ToTable("RoleTables");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Team Leader"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Team Member"
                        });
                });

            modelBuilder.Entity("Model.Status", b =>
                {
                    b.Property<int>("StatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusID"));

                    b.Property<int>("StatusOption")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("StatusID");

                    b.ToTable("StatusTables");
                });

            modelBuilder.Entity("EFrameWork.Model.Board", b =>
                {
                    b.HasOne("EFrameWork.Model.Team", "Team")
                        .WithMany("Boards")
                        .HasForeignKey("TeamID");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EFrameWork.Model.Task", b =>
                {
                    b.HasOne("EFrameWork.Model.Board", "Board")
                        .WithMany("Tasks")
                        .HasForeignKey("BoardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Status", "Status")
                        .WithMany("Tasks")
                        .HasForeignKey("StatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("EFrameWork.Model.User", b =>
                {
                    b.HasOne("EFrameWork.Model.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFrameWork.Model.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamID");

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("EFrameWork.Model.UserToTask", b =>
                {
                    b.HasOne("EFrameWork.Model.Task", "Task")
                        .WithMany("UserAssignments")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFrameWork.Model.User", "User")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EFrameWork.Model.Board", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("EFrameWork.Model.Organization", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("EFrameWork.Model.Task", b =>
                {
                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("EFrameWork.Model.Team", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("EFrameWork.Model.User", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Model.Status", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
>>>>>>>> f829845145ecca820dbbac8bcf34a8da3d3b75b6:EFrameWork/Migrations/20250515092236_InitialCreate.Designer.cs
